# Generated by Django 2.2 on 2020-07-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_author_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='author',
            name='company',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
